### ISSUE TITLE
feature request: provide an optional {{reference}} modifier

### ISSUE THREAD

**Issue by nightire** [NullVoxPopuli/ember-popperjs#22]
Currently, the `this._referenceElement` always refers to the trigger element, but in practice, some cases do not fit in this assumption.

For example, consider this UI pattern:

![example pattern](https://user-images.githubusercontent.com/1104018/136816216-48ecc645-2f3b-41a7-b119-7bbcd9b90be0.png)

1. The Trigger is the little downward triangle (with a light gray hovering background)
2. The entire button surrounded with dark gray border is the Reference
3. The Popover is the menu

Users can only show the popover menu by clicking the downward triangle precisely, but not the entire button because the whole button has a different interactive meaning here (that is, clicking to select/unselect)

However, we still need the entire button to be the reference element because we need to align the popover menu with the left side of the button as the whole, not the downward angle.

If developers can specify the reference element optionally, they can archive this pattern easily and quickly.

In our application, we use [ember-ref-bucket](https://github.com/lifeart/ember-ref-bucket) to hold a reference element and pass it to the popperjs modifier (we made our popperjs modifier before, but we would like to use this addon instead).

Maybe a better way is to provide an optional `{{reference}}` modifier, so developers can use it to assign a custom element instead of always as the same as the trigger element.

**Comment by nightire** [comment]
> for your example, I think that would look like this with ember-popperjs:
> 
> ```
> <PopperJS @placement="bottom-start" as |reference popover|>
>   <div role="button" {{reference}}>
>     <span>Some Text</span>
> 
>     <Menu >
>       <:trigger>
>         {{! this button is the trigger element }}
>         <Button />
>       </:trigger>
> 
>       <:content as |state|>
>         <List {{popover}}>
>           {{! here is the menu popover }}
>         </List>
>       </:content>
>     </Menu>
>   </div>
> </PopperJS>
> ```

Sort of, only if ember-popperjs provides the `{{reference}}` modifier, we don't need the `<Menu />` component anymore, since it also wraps the popper.js.

**Comment by NullVoxPopuli** [comment]
that's what's already provided. The thing that this addon won't do though is providing a way to manage hide/show of the popover -- too many ways to do that (or animate it! <3)

thanks for the discussion! let me know if anything is still unclear.
