### ISSUE TITLE
Collaborate with ember-popper-modifier?

### ISSUE THREAD

**Issue by jelhan** [NullVoxPopuli/ember-popperjs#229]
Are you open to collaborate in development with [ember-popper-modifier](https://github.com/NullVoxPopuli/ember-popperjs)? I see that there are different approaches on the public API design. I see benefits from both. Not saying that we should drop either or. But maybe we could reuse as much code as possible between both addons?

I haven't looked into the tiny details yet, but I have a gut feeling that ember-popper-modifier may provide the low-level primitives needed to build ember-popperjs. Having one providing low-level primitives while the other provides APIs with better developer ergonomics would be one option to draw boundaries.

My main motivation is reducing maintenance costs for overall community. Ownership shouldn't be an issue anymore since ember-popper-modifier has been moved to adopted-ember-addons org.

**Comment by NullVoxPopuli** [comment]
I don't think popper-modifier is complex enough to warrant integrating into this addon. 

This addon, as it stands, is basically one file.

_additionally_, popperjs is on the way out -- deprecated by its owners, in favor of floating-ui, which is what https://github.com/CrowdStrike/ember-velcro is using. (yea, yeah, I know, yet another popover positioning addon)

> My main motivation is reducing maintenance costs for overall community

I'm 100% all for this.

tbh, I'm probably going to archive this repo (and I think probably ember-popper-modifier should be archived, too), and then put all my time in to ember-velcro, which is way more flexible, better defaults, and then floatingui does more with less. :D

But I'm a smidge biased.

**Comment by MichalBryxi** [comment]
@NullVoxPopuli should there be a mention in the README that people should rather use ember-velcro? I think people might want to use this one and then fall into the trap of "not actually maintained"?

**Comment by NullVoxPopuli** [comment]
Yes! that's a good idea -- I'll take teh first PR that says something like that <3

**Comment by MichalBryxi** [comment]
Would this work?  #260
