### ISSUE TITLE
Issue with multiple elements on a page + in-element

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-popperjs#259]
- Having single ember-popperjs seem to be working nicely.
- When there are multiple items, it fails with:

```
Error occurred:

- While rendering:
  -top-level
    application
      multiple
        MyMenuComponent
          Menu
            PopperJS
              Items

Uncaught (in promise) DOMException: Node.removeChild: The node to be removed is not a child of this node
```

- Reproduction repo: https://gitlab.com/michal-bryxi/bugreport/ember-popperjs-bugreport
- Also related to conversation in: #244

**Comment by MichalBryxi** [comment]
Since the addon seem to be considered as deprecated (as per #229) I think this issue might be just ignored / closed. Just wanted to make sure it's google-able when someone else steps on the same rake ...

**Comment by NullVoxPopuli** [comment]
thanks for leaving a trail!
